org: oscarquerevalu
app: rimac-aws-lambda-api-app
service: rimac-aws-lambda-api
frameworkVersion: "1.54.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: serverless
  region: us-east-1

functions:
  obtener:
    handler: personaje_handler.persona
    events:
      - http:
          method: get
          path: /persona/{id}
  obtenerID:
    handler: personaje_handler.personaBD
    events:
      - http:
          method: get
          path: /personaje/{id}
  grabar:
    handler: personaje_handler.grabar
    events:
      - http:
          path: /persona
          method: post
